[tox]
envlist =
    clean,
    build,
    check,
    docs,
    #{py38,py39,py310,py311},
    py,  # generic Python3 with unspecified version using defaults
    report
ignore_basepython_conflict = true

[testenv]
basepython =
    py38: {env:TOXPYTHON:python3.8}
    py39: {env:TOXPYTHON:python3.9}
    py310: {env:TOXPYTHON:python3.10}
    py311: {env:TOXPYTHON:python3.11}
    {bootstrap,clean,build,check,report,docs, py}: {env:TOXPYTHON:python3}
setenv =
    PYTHONPATH={toxinidir}/tests
    PYTHONUNBUFFERED=yes
    # fix wrong cp1252 on Windows when loading a notebook with dash (or other unicode symbols)
    # since locale.getpreferredencoding can't be changed easily
    PYTHONUTF8=1
extras =
    tests  # Installs [project.optional-dependencies.tests]
usedevelop = false
package = wheel
# https://tox.wiki/en/latest/user_guide.html#packaging
package_env = .pkg
wheel_build_env = .pkg
commands =
    pytest --cov-config=tox.ini --cov=src --cov=tests --cov-report=term-missing -vv {posargs}

[testenv:build]
deps = build
skip_install = true
commands = python -m build

[testenv:check]
deps =
    check-manifest
    flake8
    isort
skip_install = true
commands =
    check-manifest {toxinidir}
    flake8
    isort --verbose --check-only --diff --filter-files .

[testenv:docs]
extras =
    docs  # Installs [project.optional-dependencies.docs]
usedevelop = true
# allow sh for conditional checks
allowlist_externals=sh
commands =
    #sphinx-build {posargs:-E} -b doctest docs dist/docs
    sphinx-build {posargs:-E} -b html docs dist/docs
    # run the linkcheck only if the git repo exists, maybe pure local initially
    sh -c 'test -e .git && sphinx-build -b linkcheck docs dist/docs || true'

[testenv:report]
deps =
    coverage
skip_install = true
commands =
    coverage report
    coverage html

[testenv:clean]
deps =
    coverage
skip_install = true
allowlist_externals=/bin/rm,/usr/bin/rm,rm
commands =
    coverage erase
    rm -Rf dist build htmlcov src/dobot1_control.egg-info

[flake8]
max-line-length = 120
extend-exclude =
    .ipynb_checkpoints
per-file-ignores =
    # __init__.py:F401  # example
extend-ignore = E203

# configuration for pytest-cov primarily on GitHub runners (hence the paths)
[coverage:paths]
src =
   src
   */dobot1-control/dobot1-control/src
tests =
   tests
   */dobot1-control/dobot1-control/tests

[coverage:run]
branch = true
source =
    src/dobot1_control
    tests
parallel = true

[coverage:report]
show_missing = true
precision = 2
omit = *migrations*
